services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U appuser -d appdb"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7
    ports: ["6379:6379"]

  # Kafka-compatible, no ZooKeeper needed
  redpanda:
    image: redpandadata/redpanda:v23.3.12
    command:
      - redpanda start
      - --overprovisioned
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --node-id 0
      - --check=false
      - --kafka-addr 0.0.0.0:9092
      - --advertise-kafka-addr 127.0.0.1:9092
    ports: ["9092:9092","9644:9644"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports: ["9200:9200"]

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.3
    depends_on: [ elasticsearch ]
    ports: ["5601:5601"]

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports: ["9000:9000","9001:9001"]
    volumes: ["minio:/data"]

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev --http-port=8081
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports: ["8085:8081"]

  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports: ["16686:16686","4317:4317","4318:4318"]

volumes:
  pgdata: {}
  minio: {}
