---
name: Feature Request
about: Suggest an idea for this project
title: '[FEATURE] '
labels: enhancement
assignees: ''

---

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Service Impact**
Which service(s) would this feature affect?
- [ ] jobs-service
- [ ] escrow-service
- [ ] api-gateway
- [ ] tenant-service
- [ ] auth-service
- [ ] bids-matching-service
- [ ] disputes-service
- [ ] payments-service
- [ ] notifications-service
- [ ] search-service
- [ ] analytics-service
- [ ] file-service
- [ ] admin-console

**Architecture Impact**
- [ ] Domain Model Changes
- [ ] API Changes
- [ ] Database Schema Changes
- [ ] Infrastructure Changes
- [ ] Security Changes

**Additional context**
Add any other context or screenshots about the feature request here.
