server:
  port: 8083

spring:
  application:
    name: jobs-service
  datasource:
    url: jdbc:postgresql://localhost:5432/microjobs
    username: ${DB_USERNAME:microjobs}
    password: ${DB_PASSWORD:microjobs123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: jobs
  flyway:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.microjobs.jobs: DEBUG
    org.springframework.web: DEBUG

jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: 86400000 # 24 hours