server:
  port: 8084

spring:
  application:
    name: escrow-service
  datasource:
    url: jdbc:postgresql://localhost:5432/microjobs
    username: ${DB_USERNAME:microjobs}
    password: ${DB_PASSWORD:microjobs123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: escrow
  flyway:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.microjobs.escrow: DEBUG
    org.springframework.web: DEBUG